#pragma config(Motor,  port1,           one,           tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          three,           tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Motor,  port2, 2,     tmotorNormal, openLoop)
//#pragma config(Motor,  port10, 10,     tmotorNormal, openLoop)

task main(){
	while(0==0){
		if (vexRT[Btn6U] == 1){
			motor[one]=-127;
			motor[three]=-127;
		}else{
			motor[one]=0;
			motor[three]=0;
		}
		if (vexRT[Btn6D] == 1){
			motor[one]=127;
			motor[three]=127;
		}else{
			motor[one]=0;
			motor[three]=0;
		}
	}
}
